# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Microsoft Imagine(b63b335e-ca71-4048-a17e-dabf5debe294)'
    appType: 'webAppLinux'
    WebAppName: 'PruebaProyectoTeorico'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'PYTHON|3.11'
    StartupCommand: 'gunicorn --bind=0.0.0.0  app:app'
